# Generated by Django 3.1.7 on 2024-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='saveing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
